services:
  - type: web
    name: roast-exe
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false 